### ISSUE TITLE
error when making the Clover simulator in Gazebo

### ISSUE THREAD

**Issue by pashaxe** [CopterExpress/clover_vm#5]
I run the command `catkin_make` in `**catkin_ws**.  The simulator builds up to 100% and the following error appears:

`/home/avtonomka/catkin_ws/src/sitl_gazebo/src/gazebo_camera_manager_plugin.cpp:` In member function ‘void gazebo::CameraManagerPlugin::_handle_storage_info(const mavlink_message_t*, sockaddr*)’:
/home/avtonomka/catkin_ws/src/sitl_gazebo/src/gazebo_camera_manager_plugin.cpp:779:5: error: too few arguments to function ‘uint16_t mavlink_msg_storage_information_pack_chan(uint8_t, uint8_t, uint8_t, mavlink_message_t*, uint32_t, uint8_t, uint8_t, uint8_t, float, float, float, float, float, uint8_t, const char*, uint8_t)’
  779 |     );
      |     ^
In file included from /opt/ros/noetic/include/mavlink/v2.0/common/common.h:2380,
                 from /opt/ros/noetic/include/mavlink/v2.0/common/mavlink.h:32,
                 from /home/avtonomka/catkin_ws/src/sitl_gazebo/include/gazebo_camera_manager_plugin.h:21,
                 from /home/avtonomka/catkin_ws/src/sitl_gazebo/src/gazebo_camera_manager_plugin.cpp:18:
/opt/ros/noetic/include/mavlink/v2.0/common/./mavlink_msg_storage_information.h:159:24: note: declared here
  159 | static inline uint16_t mavlink_msg_storage_information_pack_chan(uint8_t system_id, uint8_t component_id, uint8_t chan,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [sitl_gazebo/CMakeFiles/gazebo_camera_manager_plugin.dir/build.make:63: sitl_gazebo/CMakeFiles/gazebo_camera_manager_plugin.dir/src/gazebo_camera_manager_plugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:11000: sitl_gazebo/CMakeFiles/gazebo_camera_manager_plugin.dir/all] Error  2
make: *** [Makefile:163: all] Error `2

Ubuntu 20.04
Can you help me, please? Thanks!

**Comment by okalachev** [comment]
this happens when sitl_gazebo uses incorrect version of mavlink (ros one instead of px4 one).

This may be fixed using this patch: https://github.com/CopterExpress/clover_vm/blob/master/assets/patches/sitl_gazebo.patch#L1.

**Comment by pashaxe** [comment]
> this happens when sitl_gazebo uses incorrect version of mavlink (ros one instead of px4 one).
> 
> This may be fixed using this patch: https://github.com/CopterExpress/clover_vm/blob/master/assets/patches/sitl_gazebo.patch#L1.


Thank you for the answer! I'll try to do it very soon

**Comment by okalachev** [comment]
Please, try the new installation manual: https://clover.coex.tech/en/simulation_native.html.

**Comment by pashaxe** [comment]
Thank you! I used a new manual and the simulator was built without any errors
